### ISSUE TITLE
'Function not found' error for neighborhoodSplit()

### ISSUE THREAD

**Issue by ivagljiva** [thomasp85/FindMyFriends#6]
I am going through the vignette tutorial and obtaining the following error when I try to run the refinement step:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘neighborhoodSplit’ for signature ‘"pgFull"’

As far as I know, I have current versions of the general Bioconductor packages and the FindMyFriends package.

Any insight on this error would be appreciated.

**Comment by thomasp85** [comment]
`neighborhoodSplit` is only available for pgLoc subclasses as it needs chromosomal location information to work...
